### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by fire** [nmwsharp/diffusion-net#12]
Hi, when the paper is released or earlier, can you add a license text for the code?

I'm from Godot Engine so I would prefer that it is MIT-license compatible.

Amazing work.

**Comment by nmwsharp** [comment]
Glad to hear you're interested!

I simply forgot to include a license! Just added one in 18a959a

As you have guessed, an update is coming very soon with the final release of the paper, keep an eye our for it! :)

**Comment by fire** [comment]
👍
