### ISSUE TITLE
Problems with robust-laplacian 0.1.0

### ISSUE THREAD

**Issue by aschier** [nmwsharp/diffusion-net#17]
I get compilation errors when installing the dependencies, because robust-laplacian 0.1.0 seems to have problems with the namespace of Vector3. I installed the latest version (0.2.4) and it seems to work.

So maybe the dependency should just be changed to `>=0.2.4` if there is no reason against using a more recent version.

**Comment by nmwsharp** [comment]
Ah, thanks for the quick heads up. Not sure what's going on there but the newer version should certainly be safe. I just updated the `environment.yml` in aba98e99c0427b192ef6b3d6e8e56d3d30812e64. Haven't re-tested yet but hopefully that fixes.

**Comment by aschier** [comment]
I didn't use conda but pip and I probably have another compiler than you used, so a lot of things could have been the issue.
As your fix only pins the version I've installed manually, I think we can close the bug. The other packages were installed without any error.
