### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by amiltonwong** [nmwsharp/diffusion-net#27]
Hi, @nmwsharp,

From the experiment in functional correspondences, is there a typo in the last line command in README.md? Should it be :
python functional_correspondence.py --test_dataset=faust --input_features=`xyz` --load_model=pretrained_models/faust_`xyz`.pth
or
python functional_correspondence.py --test_dataset=faust --input_features=`hks` --load_model=pretrained_models/faust_`hks`.pth

**Comment by pvnieo** [comment]
Hi @amiltonwong 
Yes, it's a typo, you either use xyz features with the `faust_xyz.pth` model or the hks features with the `faust_hks.pth` model.
Thank you for noticing it, I'll correct it soon!
