### ISSUE TITLE
about visualization on shape correspondences

### ISSUE THREAD

**Issue by amiltonwong** [nmwsharp/diffusion-net#28]
Hi, @nmwsharp,

Could you release the code example about visualization on shape correspondences, like Fig. 9. in paper?

Thanks~

**Comment by pvnieo** [comment]
Hi @amiltonwong 

The figures in the paper were rendered using Blender. We don't have the specific code to produce the figures of the paper, but you can check [this repository](https://github.com/HTDerekLiu/BlenderToolbox) for examples of rendering using blender.

I Hope this will help.
